import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Archived legacy site and the client rebrand handover. Neither is built
    // by this project, and the archived code's "@/*" paths no longer resolve.
    "docs/**",
    ".open-next/**",
    // Wrangler's temporary build artifacts.
    ".wrangler/**",
    // Generated by `npm run cf-typegen`.
    "cloudflare-env.d.ts",
  ]),
]);

export default eslintConfig;
